spdx/LicenseListPublisher

resources/htmlTemplate/ExceptionHTMLTemplate.html, resources/htmlTemplate/ExceptionsTocHTMLTemplate.html, resources/htmlTemplate/LicenseHTMLTemplate.html, resources/htmlTemplate/TocHTMLTemplate.html
Adjust to the upstream redirect:
```console
$ curl -I https://spdx.linuxfound.info/sites/cpstandard/files/logo_spdx_250.png
HTTP/1.1 301 Moved Permanently
…
Location: https://spdx.org/sites/cpstandard/files/logo_spdx_250.png
…
```
Generated with:
```console
$ sed -i 's/spdx.linuxfound.info/spdx.org/g' $(git grep -l linuxfound.info)
```
=> resources/htmlTemplate: Logo moved from spdx.linuxfound.info to spdx.org

src/org/spdx/licenselistpublisher/licensegenerator/LicenseHtmlFormatWriter.java
Fixed by using the complete HTML format from the license XML specified input file
=> Improve the HTML only file format

src/org/spdx/licenselistpublisher/LicenseRDFAGenerator.java
Fixes issue where the isFsfFree flag is not being set for deprecated licenses.
=> Add metadata for deprecated licenses.  

pom.xml, src/org/spdx/htmltemplates/ExceptionHtml.java, src/org/spdx/htmltemplates/ExceptionHtmlToc.java, src/org/spdx/htmltemplates/InvalidLicenseHtmlTemplateException.java, src/org/spdx/htmltemplates/LicenseHTMLFile.java, src/org/spdx/htmltemplates/LicenseTOCHTMLFile.java, src/org/spdx/htmltemplates/package-info.java, src/org/spdx/licenselistpublisher/licensegenerator/LicenseRdfaFormatWriter.java, src/org/spdx/licenselistpublisher/licensegenerator/SpdxWebsiteFormatWriter.java, src/org/spdx/licensexml/ListedLicense.xsd
These classes are only used by the license list publisher.  Moving these classes will ease the maintenance since any changes to the license list website template can be made here and not require a dependency on the SPDX tools library.
=> Move the html template code from the SPDX tools library

src/org/spdx/htmltemplates/ExceptionHtmlToc.java, src/org/spdx/htmltemplates/LicenseTOCHTMLFile.java
=> Sort the exceptions-index.html and index.html pages

resources/htmlTemplate/TocHTMLTemplate.html
In the template for the main license list TOC, add a link to the spdx.org/ids page since the regular spdx.org website menu bar doesn't appear on the license list pages.
Fixes #46 
Signed-off-by: Steve Winslow <swinslow@gmail.com>
=> Add link to spdx.org/ids

README.md, src/org/spdx/licenselistpublisher/LicenseRDFAGenerator.java, src/org/spdx/licenselistpublisher/LicenseXmlTester.java, src/org/spdx/licensexml/XmlLicenseProviderSingleFile.java
Resolves issue #51 
WARNING: Running this with a single file will generate new index.html, licenses.json etc with only the single license or exception being represented in the file - this may overwrite existing licenses.
=> Allow for a single file to be specified in the LicenseRDFaGenerator command

src/org/spdx/crossref/CrossRefHelper.java, src/org/spdx/crossref/Live.java, src/org/spdx/crossref/Match.java, src/org/spdx/htmltemplates/LicenseHTMLFile.java, src/org/spdx/licenselistpublisher/LicenseListPublisher.java, src/org/spdx/licenselistpublisher/LicenseRDFAGenerator.java, src/org/spdx/licenselistpublisher/licensegenerator/ILicenseFormatWriter.java, src/org/spdx/licenselistpublisher/licensegenerator/ILicenseTester.java, src/org/spdx/licenselistpublisher/licensegenerator/LicenseTester.java, src/org/spdx/licenselistpublisher/licensegenerator/SimpleLicenseTester.java
=> Add license text from the test files to resolve text formatting issues

src/org/spdx/licenselistpublisher/LicenseRDFAGenerator.java, src/org/spdx/licenselistpublisher/licensegenerator/LicenseTextFormatWriter.java
This will allow the canonical text to be used as long as the License-List-XML repo has canonical text as the test text.
=> Remove word wrapping for text file generation if test text is used

resources/htmlTemplate/ExceptionsTocHTMLTemplate.html, resources/htmlTemplate/TocHTMLTemplate.html
update description and links to be current
=> update description and links

src/org/spdx/htmltemplates/LicenseHTMLFile.java
This fixes a bug introduced by PR #109 which removed getSet() from the Formatted URL class causing the generated HTML files to be missing the text for the cross reference links in the License HTML pages.
=> Add getSite() back to FormattedURL

pom.xml
JSoup is already included as a dependency in the Spdx-Java-Library which is included as a dependency - there is no need to include it in this project.
=> Remove JSoup dependency

resources/htmlTemplate/ExceptionHTMLTemplate.html, resources/htmlTemplate/ExceptionsTocHTMLTemplate.html, resources/htmlTemplate/LicenseHTMLTemplate.html, resources/htmlTemplate/TocHTMLTemplate.html
This commit changes the colour of the text in the generated website from light blue to the dark blue of the SPDX logo, in order to meet Level AAA of the Web Content Accessibility Guidelines (WCAG) for contrast.
See also <https://github.com/spdx/spdx-spec/pull/574>, which made this change (and other contrast improvements) to the SPDX specification website.
=> Improve contrast of the generated website

pom.xml
Updates log4j to version 2.17.0 resolving possible vulnerabilities
CVE-2021-44228 and CVE-2021-45046
Note that the current usage of the licenseListPublisher makes it unlikely this vulnerability would be exploited.
=> Update SPDX Library version to 1.0.10

resources/htmlTemplate/LicenseHTMLTemplate.html
Clarify that the SPDX license identifier, and not the license itself,
is deprecated.
Signed-off-by: John Neffenger <john@status6.com>
=> Clarify that the license identifier is deprecated

resources/htmlTemplate/TocHTMLTemplate.html
[The SPDX License List FAQ][1] tries to draw attention to the information written before the tables on [the SPDX License List Web page][2]. The FAQ does this for a reason: [“This is based on my observation that many people seem to view the webpage at https://spdx.org/licenses/ - and just look at the list (literally) there, skipping over the other information at the top of the page that explains context, bigger picture, etc.”][3]
[At the moment, the FAQ tries to draw attention to those sections in an awkward and slightly incorrect way][4]. This commit gives those sections anchors so that spdx/license-list-XML#1826 can add direct links to them.
[1]: <https://github.com/spdx/license-list-XML/blob/main/DOCS/faq.md>
[2]: <https://spdx.org/licenses/>
[3]: …
=> Add anchors for the preamble and deprecated id list

resources/htmlTemplate/ExceptionHTMLTemplate.html, resources/htmlTemplate/LicenseHTMLTemplate.html, src/org/spdx/licensexml/LicenseXmlHelper.java
Fixes #165
Here's a screenshot of the current implementation:
=> Add hover text and explanation of red/blue text

src/org/spdx/licenselistpublisher/LicenseRDFAGenerator.java
Fix typo of a parameter of `generateLicenseData()` from src/org/spdx/licenselistpublisher/LicenseRDFAGenerator.java:
- releaseDateUnformated -> releaseDateUnformatted
This is a change in code, but it should consider as safe, because it is the name of parameter, not the method, class, interface, or enum.
The spelling will match with a parameter `unformattedDate` of `convertDateFormat()`.
=> Fix typo: releaseDateUnformated -> releaseDateUnformatted

CONTRIBUTING.md, README.md, src/org/spdx/htmltemplates/package-info.java, src/org/spdx/licenselistpublisher/LicenseRDFAGenerator.java, src/org/spdx/licenselistpublisher/MarkdownTable.java, src/org/spdx/licenselistpublisher/licensegenerator/LicenseMarkdownFormatWriter.java
- Remove Travis CI badge (not active)
- Add TestLicenseXML testDirectory parameter
- Fix typo in usage:
- licencenseXmlFileOrDir -> licenseXmlFileOrDir
- This is a parameter name, not a function name, so it is safe to fix it and not breaking existing command lines 
- Fix other typos
=> Update README and fix typos

src/org/spdx/htmltemplates/ExceptionHtml.java, src/org/spdx/htmltemplates/ExceptionHtmlToc.java, src/org/spdx/htmltemplates/LicenseHTMLFile.java, src/org/spdx/htmltemplates/LicenseTOCHTMLFile.java, src/org/spdx/htmltemplates/Utility.java
Resolves an issue where file system HTML templates causes an error if run on a windows platform
=> Use class and file resolvers for Mustache

resources/licenses-full.json
Updates the FSF status in the licenses based on the current FSF website as of 18 June 2025.
Fixes #213
Also adds status from MIT-0 and Unicode-3.0
=> Vendor FSF license status JSON file from fsf-api
