- src/org/spdx/licensexml/LicenseXmlHelper.java
Fixes issue reported on SPDX license list XML https://github.com/spdx/license-list-XML/issues/615
> Fix br tags to include close for proper XHTML parsing

- Test/org/spdx/licensexml/LicenseXmlDocumentTest.java
- src/org/spdx/licenselistpublisher/licensegenerator/LicenseTextFormatWriter.java
- src/org/spdx/licensexml/LicenseXmlHelper.java
> Fix text formatting

- resources/htmlTemplate/ExceptionHTMLTemplate.html
- resources/htmlTemplate/ExceptionsTocHTMLTemplate.html
- resources/htmlTemplate/LicenseHTMLTemplate.html
- resources/htmlTemplate/TocHTMLTemplate.html
> Update copyright. 

- src/org/spdx/licenselistpublisher/licensegenerator/LicenseRdfFormatWriter.java
- src/org/spdx/licenselistpublisher/licensegenerator/SpdxWebsiteFormatWriter.java
This will enable the SPDX tools to more efficiently read the license list data.
> Add JSON-LD format to website

- resources/htmlTemplate/ExceptionHTMLTemplate.html
- resources/htmlTemplate/ExceptionsTocHTMLTemplate.html
- resources/htmlTemplate/LicenseHTMLTemplate.html
- resources/htmlTemplate/TocHTMLTemplate.html
- src/org/spdx/licensexml/LicenseXmlHelper.java
Fixes https://github.com/spdx/license-list-data/issues/33 
> Fix XML parsing issue with &copyright

- src/org/spdx/licenselistpublisher/licensegenerator/LicenseHtmlFormatWriter.java
Fixes #32 for me. Maybe there's a better way, including maybe there's something wrong about my setup that should be fixed. Feel free to ignore!
> replace replacement character with hex code for replacement character

- resources/htmlTemplate/TocHTMLTemplate.html
> update "Deprecated..." section header

- README.md
- src/org/spdx/licenselistpublisher/LicenseXmlTester.java
- src/org/spdx/licenselistpublisher/Main.java
Support a solution for https://github.com/spdx/LicenseListPublisher/issues/50
> Add command to test a single license XML file.

- src/org/spdx/licensexml/LicenseXmlDocument.java
> Fix issue #49 - line feeds in URL's

- pom.xml
- resources/htmlTemplate/ExceptionHTMLTemplate.html
- resources/htmlTemplate/LicenseHTMLTemplate.html
> Fix issue #57: rendering colors for optional text

- src/org/spdx/htmltemplates/ExceptionHtmlToc.java
- src/org/spdx/htmltemplates/LicenseTOCHTMLFile.java
> Resolve issue #56 - fix sorting of exceptions

- resources/htmlTemplate/ExceptionsTocHTMLTemplate.html
- resources/htmlTemplate/TocHTMLTemplate.html
> Remove text column - resolves issue #18

- src/org/spdx/licensexml/LicenseXmlHelper.java
- src/org/spdx/licensexml/ListedLicense.xsd
resolves issue #87 
Also removes an extra newline in the HTML generated for alt text.
> Implements spacing attribute for alt text

- Test/org/spdx/licensexml/LicenseXmlDocumentTest.java
- TestFiles/BSD-Protection.xml
- pom.xml
- src/org/spdx/licenselistpublisher/LicenseRDFAGenerator.java
- src/org/spdx/licensexml/LicenseXmlHelper.java
Resolves issue #95 
Also resolves an issue formatting text and templates with paragraph tags
> Check for duplicate licenses for single file publishing

- Test/org/spdx/licensexml/LicenseXmlDocumentTest.java
- pom.xml
- src/org/spdx/licensexml/LicenseXmlHelper.java
> Increase limit on copyright text size from 1000 to 5000 characters

- resources/htmlTemplate/TocHTMLTemplate.html
see https://github.com/spdx/license-list-XML/issues/1082 for more info
> update deprecation description

- src/org/spdx/licensexml/LicenseXmlHelper.java
Close https://github.com/spdx/LicenseListPublisher/issues/106
> Close #106

- src/org/spdx/licensexml/LicenseXmlHelper.java
> Add text nodes embedded in the list items

- src/org/spdx/licenselistpublisher/licensegenerator/FsfLicenseDataParser.java
Resolves https://github.com/spdx/spdx-spec/issues/93
> Add isFsfLibre=false for any licenses tagged as non-free in by the fsf-api

- src/org/spdx/licensexml/LicenseXmlHelper.java
Resolves https://github.com/spdx/license-list-XML/pull/1331#issuecomment-917494288
> Add spaces in HTML per spacing attribute

- src/org/spdx/crossref/Timestamp.java
> Change timestamp format for CrossRef to the SPDX standard

- .github/workflows/build.yml
> Check for sonar credentials in Github Action

- Test/org/spdx/crossref/OsiApiTest.java
- src/org/spdx/crossref/CrossRefHelper.java
- src/org/spdx/crossref/OsiApi.java
- src/org/spdx/crossref/OsiLicense.java
> Use OSI API to check cross ref links

- pom.xml
- src/org/spdx/licenselistpublisher/licensegenerator/LicenseJsonFormatWriter.java
- src/org/spdx/storage/listedlicense/SortableExceptionJsonTOC.java
> Sort the JSON TOC files

- src/org/spdx/licensexml/ListedLicense.xsd
NOTE: This PR should NOT be merged until all the license XML's have been fixed and https://github.com/spdx/license-list-XML/pull/1681 has been merged.
> Update schema with changes in license-list-XML PR #1681

- TestFiles/BSD-Protection.xml
> Fix unit test failure caused by schema update

- pom.xml
> Update Java Libraries to version 1.1.3

- CONTRIBUTING.md
See individual commit messages for details.
> Fix capitalization & make link less misleading

- pom.xml
> Update libraries to version 1.1.4

- src/org/spdx/licenselistpublisher/licensegenerator/SpdxWebsiteFormatWriter.java
> Add exception HTML file with no html extension to website

- Test/org/spdx/licensexml/LicenseXmlDocumentTest.java
- src/org/spdx/licensexml/LicenseXmlHelper.java
> Only add one lf for line breaks converting to text

- src/org/spdx/licenselistpublisher/LicenseXmlTester.java
- src/org/spdx/licenselistpublisher/Main.java
Fixes issue discussed in https://github.com/spdx/license-list-XML/pull/2636#issuecomment-2553185321
> Fix test single license command

- Test/org/spdx/licenselistpublisher/LicenseXmlTesterTest.java
- TestFiles/BSD-3-Clause.xml
- TestFiles/bad-tests/BSD-3-Clause/license/bad/must-not-reproduce.txt
- TestFiles/bad-tests/BSD-3-Clause/license/good/changed-copyright.txt
- TestFiles/bad-tests/BSD-3-Clause/license/good/must-not-reproduce.txt
- TestFiles/bad-tests/BSD-3-Clause/license/good/original.txt
- TestFiles/good-tests/BSD-3-Clause/license/bad/must-not-reproduce.txt
- TestFiles/good-tests/BSD-3-Clause/license/good/changed-copyright.txt
- TestFiles/good-tests/BSD-3-Clause/license/good/original.txt
- src/org/spdx/licenselistpublisher/LicenseRDFAGenerator.java
- src/org/spdx/licenselistpublisher/LicenseXmlTester.java
- src/org/spdx/licenselistpublisher/licensegenerator/CombinedLicenseTester.java
- src/org/spdx/licenselistpublisher/licensegenerator/ILicenseTester.java
- src/org/spdx/licenselistpublisher/licensegenerator/LicenseTester.java
- src/org/spdx/licenselistpublisher/licensegenerator/SimpleLicenseTester.java
Adds an extra option at the end of `TestLicenseXML` and `LicenseRDFAGenerator` for a full license test.
> Add option for full testing

- src/org/spdx/htmltemplates/LicenseHTMLFile.java
Removed a redundant check in the getTimestamp() method, as the timestamp is explicitly set to 'N/A' in the constructor. Also removed unnecessary null checks as discussed in #197
> Refactored LicenseHTMLFile.java

- pom.xml
- spdx-maven-plugin to 1.0.0
- Other dependencies to latest patch version
- Also grouped org.spdx and commons-* deps together.
> Update spdx-maven-plugin to 1.0.0 and other dependencies to latest patch version

- src/org/spdx/htmltemplates/LicenseHTMLFile.java
Fixes #206
Brings the time back down to pre-3.1 levels.
> Only check isValid when needed

- resources/licenses-full.json
- src/org/spdx/licenselistpublisher/LicenseRDFAGenerator.java
Non ignored warnings are now printed after the ignored warnings
> Improve warning messages
